ROUTING_KEYWORDS = {
    "nlp": [
        "review",
        "reviews",
        "feedback",
        "sentiment",
        "summary",
        "summaries",
        "summarize",
        "summarise",
        "keyword",
        "keywords",
        "comment",
        "comments",
        "text",
        "opinion",
        "opinions",
        "good",
        "bad",
        "late",
        "delivery",
        "complaint",
        "complaints",
    ],
    "ml": [
        "sales",
        "revenue",
        "trend",
        "trends",
        "data",
        "profit",
        "analytics",
        "performance",
        "metric",
        "metrics",
        "forecast",
        "average",
        "averages",
        "insight",
        "insights",
    ],
    "cv": [
        "image",
        "images",
        "photo",
        "photos",
        "picture",
        "pictures",
        "object",
        "objects",
        "visual",
        "visuals",
        "scan",
        "scans",
        "screenshot",
        "screenshots",
        "ocr",
        "label",
        "labels",
    ],
    "rag": [
        "document",
        "documents",
        "policy",
        "retrieve",
        "retrieval",
        "knowledge",
        "lookup",
        "docs",
    ],
}

ROUTING_PHRASES = {
    "nlp": [
        "customer feedback",
        "customer review",
        "customer reviews",
        "product review",
        "product reviews",
        "sentiment analysis",
        "mixed sentiment",
        "good but late",
        "bad service",
        "review summary",
        "review summaries",
        "summarize customer reviews",
        "keyword extraction",
    ],
    "ml": [
        "sales data",
        "revenue trend",
        "revenue trends",
        "sales analytics",
        "sales insight",
        "sales insights",
        "trend analysis",
        "average sales",
        "average revenue",
        "performance metrics",
        "profit analysis",
    ],
    "cv": [
        "analyze image",
        "analyze photo",
        "process image",
        "visual analysis",
        "detect object",
        "ocr image",
        "ocr this image",
        "label image",
        "label this image",
        "describe image",
        "image labels",
        "image description",
        "extract text from image",
    ],
    "rag": [
        "sales dropped",
        "why sales dropped",
        "search docs",
        "search documents",
        "search document",
        "search policy document",
        "retrieve document",
        "retrieve from knowledge base",
        "knowledge base",
        "policy lookup",
        "policy document",
        "look up policy",
    ],
}

ROUTE_MESSAGES = {
    "nlp": "Route to NLP service for text analysis",
    "ml": "Route to ML service for data analysis",
    "cv": "Route to CV service for image analysis",
    "rag": "Route to RAG service for knowledge retrieval",
}
