ROUTING_KEYWORDS = {
    "nlp": [
        "review",
        "reviews",
        "feedback",
        "sentiment",
        "comment",
        "comments",
        "text",
        "opinion",
        "opinions",
        "good",
        "bad",
        "late",
        "delivery",
        "complaint",
        "complaints",
        "product",
    ],
    "ml": [
        "sales",
        "revenue",
        "trend",
        "trends",
        "data",
        "profit",
        "analytics",
        "performance",
        "metric",
        "metrics",
        "forecast",
    ],
    "cv": [
        "image",
        "photo",
        "picture",
        "object",
        "visual",
        "scan",
        "screenshot",
    ],
    "rag": [
        "document",
        "policy",
        "search",
        "retrieve",
        "knowledge",
        "lookup",
        "reason",
        "reasons",
        "why",
        "context",
        "source",
        "explain",
    ],
}

ROUTING_PHRASES = {
    "nlp": [
        "customer feedback",
        "customer review",
        "customer reviews",
        "product review",
        "product reviews",
        "sentiment analysis",
        "mixed sentiment",
        "good but late",
        "bad service",
    ],
    "ml": [
        "sales data",
        "revenue trend",
        "revenue trends",
        "sales analytics",
        "performance metrics",
        "profit analysis",
    ],
    "cv": [
        "analyze image",
        "analyze photo",
        "process image",
        "visual analysis",
        "detect object",
        "extract text from image",
    ],
    "rag": [
        "sales dropped",
        "why sales dropped",
        "delivery delay reason",
        "search document",
        "retrieve document",
        "knowledge base",
        "policy document",
        "look up policy",
    ],
}

ROUTE_MESSAGES = {
    "nlp": "Route to NLP service for text analysis",
    "ml": "Route to ML service for data analysis",
    "cv": "Route to CV service for image analysis",
    "rag": "Route to RAG service for knowledge retrieval",
}
