import requests
import json


def ask_llm(query: str, candidates: list) -> list:
    try:
        prompt = f"""
You are an intelligent AI routing validator for an AI Business Intelligence platform.

Your role is to semantically validate and refine routing decisions generated by a rule-based routing engine.

Your responsibilities:
1. Analyze the true semantic meaning and workflow intent of the query.
2. Validate the candidate modules generated by the rule engine.
3. Remove irrelevant modules if incorrectly suggested.
4. Add missing modules if required by the query intent.
5. Detect multi-intent and multi-stage workflows.
6. Return ALL modules necessary to fully process the query.
7. Order modules by logical execution priority.
8. Compensate for weaknesses in keyword-based routing.
9. Handle paraphrasing, indirect wording, ambiguous phrasing, and semantic meaning.
10. Prefer complete workflow routing over minimal routing.

Available modules:

- nlp
Used for:
sentiment analysis,
feedback analysis,
review analysis,
summaries,
text understanding,
language processing,
comment analysis,
text-based insight extraction

- ml
Used for:
forecasting,
predictions,
trend analysis,
sales analysis,
revenue analytics,
metrics,
business insights,
numerical analysis,
data-driven forecasting

- cv
Used for:
image analysis,
video analysis,
object detection,
camera/CCTV understanding,
visual recognition,
visual content interpretation

- genai
Used for:
report generation,
content creation,
descriptions,
explanations,
writing tasks,
generated responses,
final response generation

User Query:
"{query}"

Rule-engine candidate modules:
{candidates}

IMPORTANT ROUTING RULES:

- Queries may require MULTIPLE modules.
- Return ALL modules needed to completely handle the query.
- Modules must be ordered by execution priority.
- Earlier modules may prepare outputs for later modules.
- Do NOT return only one module if multiple modules are required.
- Do NOT trust rule-engine candidates blindly.
- Add missing modules if semantic intent requires them.
- Remove irrelevant modules if necessary.
- Prefer complete and accurate workflow routing.
- Never invent new module names.
- Only use:
["nlp", "ml", "cv", "genai"]

OUTPUT RULES:

- Return ONLY a valid JSON list.
- Do NOT return explanations.
- Do NOT return markdown.
- Do NOT return reasoning text.
- Do NOT return anything outside JSON.

Examples:

Query:
"give me summary and feedback of sales trend prediction"
Correct Output:
["ml", "nlp"]

Reasoning:
ML performs trend/prediction analysis first.
NLP summarizes and analyzes feedback afterward.

Query:
"generate report from customer feedback"
Correct Output:
["nlp", "genai"]

Reasoning:
NLP analyzes customer feedback first.
GENAI generates the final report afterward.

Query:
"detect objects from CCTV footage and explain findings"
Correct Output:
["cv", "genai"]

Reasoning:
CV performs object detection first.
GENAI explains and generates readable output afterward.

Query:
"summarize sales trends and forecast future revenue"
Correct Output:
["ml", "nlp"]

Reasoning:
ML performs forecasting/trend analysis first.
NLP summarizes the analytical insights afterward.

Query:
"analyze customer sentiment and create executive report"
Correct Output:
["nlp", "genai"]

Query:
"analyze video footage and generate incident summary"
Correct Output:
["cv", "genai"]

Return ONLY valid JSON list.
"""

        response = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": "phi3",
                "prompt": prompt,
                "stream": False
            },
            timeout=30
        )

        result = response.json()["response"].strip()

        # Safe JSON extraction
        start = result.find("[")
        end = result.rfind("]")

        if start == -1 or end == -1:
            return candidates

        cleaned = result[start:end + 1]

        modules = json.loads(cleaned)

        # Remove duplicates while preserving order
        modules = list(dict.fromkeys(modules))

        # Empty fallback
        if not modules:
            return candidates

        # Validation
        valid_modules = {"nlp", "ml", "cv", "genai"}

        if (
            not isinstance(modules, list)
            or not all(m in valid_modules for m in modules)
        ):
            return candidates

        return modules

    except Exception:
        return candidates